server:
  port: 8078

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/hungli
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  main:
     allow-circular-references: true

#解决添加swagger之后启动报错问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
